### ISSUE TITLE
Monolisa link doesn't work

### ISSUE THREAD

**Issue by kndshein** [TkDodo/blog#191]
Hi! Big fan of your write-up on React-Query. Just noticed that your monolisa.dev (affiliate?) link is broken. FYI. :)

**Comment by TkDodo** [comment]
Thanks for reporting. I'll try to find out what's wrong asap

**Comment by TkDodo** [comment]
I had to remove the link for now until the guys at mono lisa have figured out a different provider than paddle it seems.
