### ISSUE TITLE
Gatsby caching issue?

### ISSUE THREAD

**Issue by Josh68** [TkDodo/blog#234]
Hi. I enjoyed reading https://tkdodo.eu/blog/avoiding-use-effect-with-callback-refs, thanks.

However (in Chrome), I could only see/read it after I hard-refreshed with a cache clear (even after another, plain page refresh, the entire page disappears). In my past experience with Gatsby, this could be due to a PWA/caching config, not sure.

Don't know if I'm the only one experiencing this, but I'm sure you'd rather not have people see blank pages when they find your posts.

**Comment by Josh68** [comment]
I should say the issue cleared up for me right after I wrote this, and I don't know how to recreate it. But it happened to me many times. I suppose close if you can't reproduce.

**Comment by TkDodo** [comment]
hm, sorry for that. I'll move away from gatsby eventually 😅
