### ISSUE TITLE
GUEST AUTHORING

### ISSUE THREAD

**Issue by DeveloperAspire** [TkDodo/blog#251]
Hello, @TkDodo, Happy new year.

My name is Franklin Okolie. I am a Frontend Engineer who is passionate about building web applications and sharing knowledge about my learnings through technical writing.

As a follower of your blog, I have learnt a lot from the publication and I will say I am excited to be pitching the idea that I will also love be an author for the publication and it would be a great honor to do so.

I have an amazing track record of writing clear and concise articles, I was recognized as one of the top 10 Freecodecamp authors for 2023, a testament to my exceptional skills and dedication to the field of technical writing, [Top 10 Freecodecamp Authors](https://www.freecodecamp.org/news/top-open-source-contributors-2023/), I also maintain a perosonal blog on [Hashnode](https://hashnode.com/@Franklin86)

I am excited to propose an article idea that I am confident will captivate the your interest and provide valuable insights for the readers of this esteemed publication.

**ARTICLE TOPIC**: **Object Typing Demystified: TypeScript Interface vs. Type Annotations - Unraveling the Best Approach**

I have an outline and a summary for this prepared down for review upon request by you.

I look forward to your reponse.

**Comment by TkDodo** [comment]
sorry, I don't really do guest posts.
