### ISSUE TITLE
Typo in "Thinking in React Query"

### ISSUE THREAD

**Issue by snow-t-m-yang** [TkDodo/blog#306]
Hi TkDodo,

In here:

https://github.com/TkDodo/blog/blob/b17895d71ee595ce7dd154779f7bf1bd0f3d3d6f/src/components/thinking-in-react-query/index.tsx#L393

Maybe there is missing a space.

Really appreciated your work for us to learn more about React Query.

**Comment by TkDodo** [comment]
is this about “blopost” vs “blog post” ? I’ve used both interchangeably. If it bothers you, please file a PR.

**Comment by snow-t-m-yang** [comment]
Em... Interesting, didn't know that's a word, never mind then.
